#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define APP_MODE_HEARTBEAT 1
#define APP_MODE_K230_UART 2
#define APP_MODE_MOTOR_PWM 3
#define APP_MODE_CCD_ADC   4
#define APP_MODE_UART_TEST 5
#define APP_MODE_CCD_WATCH 6
#define APP_MODE_LINE_FOLLOW 7
#define APP_MODE_CCD_STRAIGHT 8
#define APP_MODE_ENCODER_WATCH 9
#define APP_MODE_SPEED_TEST 10
#define APP_MODE_CIRCLE_FOLLOW 11
#define APP_MODE_K230_FOLLOW 12
#define APP_MODE_SQUARE_FOLLOW 13

#define APP_MODE APP_MODE_SQUARE_FOLLOW

#endif
