#ifndef BSP_MOTOR_H
#define BSP_MOTOR_H

#include <stdint.h>

void Bsp_Motor_Init(void);
void Bsp_Motor_Disable(void);
void Bsp_Motor_Stop(void);
void Bsp_Motor_Coast(void);
void Bsp_Motor_Set(float left_ratio, float right_ratio);
void Bsp_Motor_SetLeftRaw(uint8_t dir_high, uint32_t compare);
void Bsp_Motor_SetRightRaw(uint8_t dir_high, uint32_t compare);
void Bsp_Motor_EncoderInit(void); // Start the 2025-style hardware edge counters for both encoders.
void Bsp_Motor_EncoderReset(void); // Clear accumulated encoder position and sampled speed counts.
void Bsp_Motor_EncoderSample(void); // Convert accumulated encoder position changes into per-sample speeds.
int32_t Bsp_Motor_GetLeftEncoderCount(void); // Return the logical left accumulated encoder count.
int32_t Bsp_Motor_GetRightEncoderCount(void); // Return the logical right accumulated encoder count.
int16_t Bsp_Motor_GetLeftEncoderSpeed(void); // Return logical left encoder ticks from the latest sample window.
int16_t Bsp_Motor_GetRightEncoderSpeed(void); // Return logical right encoder ticks from the latest sample window.
void Bsp_Motor_SpeedPidInit(void); // Initialize the two wheel-speed PI controllers.
void Bsp_Motor_SpeedPidReset(void); // Reset wheel-speed PI state before starting a new closed-loop run.
void Bsp_Motor_SetSpeedTargets(float left_cm_s, float right_cm_s); // Set requested wheel speeds in cm/s.
void Bsp_Motor_SpeedPidUpdate(void); // Sample encoders, run wheel-speed PI, and update motor PWM.
void Bsp_Motor_SpeedPidStop(void); // Stop the motor and clear closed-loop speed commands.
float Bsp_Motor_GetLeftSpeedTarget(void); // Return logical left slew-limited target speed in cm/s.
float Bsp_Motor_GetRightSpeedTarget(void); // Return logical right slew-limited target speed in cm/s.
float Bsp_Motor_GetLeftSpeedCommand(void); // Return logical left PWM ratio generated by the speed PI loop.
float Bsp_Motor_GetRightSpeedCommand(void); // Return logical right PWM ratio generated by the speed PI loop.
float Bsp_Motor_GetLeftMeasuredSpeed(void); // Return filtered logical left speed in cm/s.
float Bsp_Motor_GetRightMeasuredSpeed(void); // Return filtered logical right speed in cm/s.
float Bsp_Motor_GetLeftSpeedPTerm(void); // Return logical left proportional PWM contribution.
float Bsp_Motor_GetRightSpeedPTerm(void); // Return logical right proportional PWM contribution.
float Bsp_Motor_GetLeftSpeedITerm(void); // Return logical left integral PWM contribution.
float Bsp_Motor_GetRightSpeedITerm(void); // Return logical right integral PWM contribution.
uint32_t Bsp_Motor_GetSpeedFaults(void); // Return encoder-loss fault bits: left bit 0, right bit 1.

#endif
