/**
 * @file bsp_motor.c
 * @brief 双路电机 PWM、H 桥状态、编码器计数和左右轮速度闭环实现。
 *
 * 本模块统一修正逻辑左右轮与物理接线方向；编码器 ISR 只累计位置，速度和控制计算在主循环完成。
 */
#include "bsp_motor.h"

#include <stdint.h>
#include "ti_msp_dl_config.h"

/* PWM 周期和应用允许的最大比例指令；保留余量用于实车调试安全。 */
#define BSP_MOTOR_PWM_PERIOD 10000U
#define BSP_MOTOR_MAX_RATIO  0.80f
/*
 * 逻辑轮到物理接线的方向和正反向修正系数。
 * 正逻辑指令必须让对应物理轮前进；左右修正值跟随电机本体，而不是连接器位置。
 */
#define BSP_MOTOR_LEFT_DIR    1.0f // Positive logical command must drive the physical-left wheel forward.
#define BSP_MOTOR_RIGHT_DIR   1.0f // Positive logical command must drive the physical-right wheel forward.
#define BSP_MOTOR_LEFT_FORWARD_SCALE  1.00f // Keep the physical-left motor trim with that motor after the connector swap.
#define BSP_MOTOR_RIGHT_FORWARD_SCALE 0.85f // Keep the physical-right motor trim with that motor after the connector swap.
#define BSP_MOTOR_LEFT_REVERSE_SCALE  1.00f // Physical-left reverse trim.
#define BSP_MOTOR_RIGHT_REVERSE_SCALE 0.91f // Physical-right reverse trim.
/*
 * 编码器换算参数：轮径 6.5 cm，每圈 14000 个 A 相硬件边沿，定时器每 10 个边沿产生一次软件计数。
 * 应用以 20 ms 采样，TICK_TO_CM_S 将窗口内软件计数直接换算为轮缘线速度。
 */
#define BSP_MOTOR_ENCODER_WHEEL_DIAMETER_CM 6.5f // Same 65 mm wheel diameter used by the 2025 and STM32 projects.
#define BSP_MOTOR_ENCODER_EDGES_PER_REV 14000.0f // A-phase edges per wheel revolution from the 2025 GMR motor definition.
#define BSP_MOTOR_ENCODER_EDGE_BATCH 10.0f // Match the 2025 same-car edge counter: one software count per ten A-phase edges.
#define BSP_MOTOR_SPEED_SAMPLE_SECONDS 0.020f // The application calls the speed loop every 20 ms.
#define BSP_MOTOR_ENCODER_TICK_TO_CM \
    ((3.14159265f * BSP_MOTOR_ENCODER_WHEEL_DIAMETER_CM * BSP_MOTOR_ENCODER_EDGE_BATCH) / \
     BSP_MOTOR_ENCODER_EDGES_PER_REV)
#define BSP_MOTOR_ENCODER_TICK_TO_CM_S \
    (BSP_MOTOR_ENCODER_TICK_TO_CM / BSP_MOTOR_SPEED_SAMPLE_SECONDS)
/*
 * 轮速闭环调参。
 * 目标先限幅并按步长逼近；测量值可滤波；控制器包含 P/I/D 项、条件积分、启动 kick 和输出限幅。
 * stall 计数仅设置实时故障位，不会在底层突然制动，安全策略由应用层决定。
 */
#define BSP_MOTOR_SPEED_TARGET_LIMIT_CM_S 60.0f // Reject accidental targets outside the first-stage test envelope.
#define BSP_MOTOR_SPEED_TARGET_SLEW_CM_S 60.0f // Follow CCD wheel targets in one update; the verified CCD and PWM slew limits provide smoothing.
#define BSP_MOTOR_SPEED_FILTER_ALPHA 1.00f // Match the 2025 same-car controller: use each measured window directly.
#define BSP_MOTOR_SPEED_PID_KP 0.0050f // 2025 Kp=0.5 followed by /100 PWM conversion.
#define BSP_MOTOR_SPEED_PID_KI 0.0010f // 2025 Ki=0.1 followed by /100 PWM conversion.
#define BSP_MOTOR_SPEED_PID_KD 0.0005f // 2025 Kd=0.05 followed by /100 PWM conversion.
#define BSP_MOTOR_SPEED_PID_START 0.0f // 2025 applies 10 percent once at start, not as a permanent feed-forward bias.
#define BSP_MOTOR_SPEED_PID_FULL_START_CM_S 10.0f // Scale startup bias below 10 cm/s so a bend's inner wheel can nearly stop.
#define BSP_MOTOR_SPEED_PID_ERROR_INT_THRESHOLD 50.0f // Match the 2025 error window for enabling integration.
#define BSP_MOTOR_SPEED_PID_INTEGRAL_LIMIT 500.0f // With Ki=0.001 this matches the 2025 50-percent integral ceiling.
#define BSP_MOTOR_SPEED_PID_OUTPUT_LIMIT 0.50f // Match the 2025 speed-PID output ceiling for the standalone test.
#define BSP_MOTOR_SPEED_PWM_ACCEL_SLEW_LIMIT 1.0f // The 2025 controller writes each new PID output directly.
#define BSP_MOTOR_SPEED_PWM_DECEL_SLEW_LIMIT 1.0f // The 2025 controller does not add a separate output slew limiter.
#define BSP_MOTOR_SPEED_STARTUP_KICK_MIN_TARGET_CM_S 10.0f // Do not kick a bend's nearly stopped inner wheel.
#define BSP_MOTOR_SPEED_STARTUP_KICK_PWM 0.10f // Match DC_Start(): apply ten-percent PWM before the first PID result.
#define BSP_MOTOR_SPEED_STARTUP_KICK_WINDOWS 1U // 2025 gives the direct start command once, then hands control to PID.
#define BSP_MOTOR_SPEED_STALL_MIN_TARGET_CM_S 5.0f // Ignore no-pulse detection while nearly stopped.
#define BSP_MOTOR_SPEED_STALL_MIN_PWM 0.18f // Start stall timing only after enough PWM should move a lifted wheel.
#define BSP_MOTOR_SPEED_STALL_WINDOWS 25U // Stop after 500 ms with commanded motion but no encoder batches.

/* 单个逻辑轮的速度控制状态，所有速度字段单位为 cm/s，command/P/I 为 PWM 比例贡献。 */
typedef struct {
    float requested_target; // Requested wheel speed in cm/s before the acceleration ramp.
    float target; // Slew-limited wheel speed target in cm/s used by this update.
    float measured; // Filtered measured wheel speed magnitude in cm/s.
    float integral; // Accumulated speed error in cm/s samples.
    float last_error; // Previous speed error used by the derivative term.
    float command; // Latest PWM ratio generated by the speed PI loop.
    float p_term; // Latest proportional contribution for debugger tuning.
    float i_term; // Latest integral contribution for debugger tuning.
    uint8_t startup_kick_windows; // Remaining direct-start samples before normal PI output takes over.
    uint16_t zero_tick_windows; // Consecutive driven samples with no encoder batches.
    uint8_t fault; // Live diagnostic flag; one means encoder batches disappeared under drive.
} MotorSpeedPid;

/*
 * 编码器 ISR 累计位置和主循环采样基线。
 * volatile 只用于中断共享；逻辑左右映射已经按当前六线电机接口修正。
 */
static volatile int32_t s_encoder_old_left_count = 0; // Raw old-left encoder position from PB13/PB20.
static volatile int32_t s_encoder_old_right_count = 0; // Raw old-right encoder position from PB15/PB17.
static int32_t s_encoder_left_last_count = 0; // Previous logical-left count used to form sample speed.
static int32_t s_encoder_right_last_count = 0; // Previous logical-right count used to form sample speed.
static int16_t s_encoder_left_speed = 0; // Latest logical-left signed tick delta per sample.
static int16_t s_encoder_right_speed = 0; // Latest logical-right signed tick delta per sample.
static MotorSpeedPid s_left_speed_pid = {0}; // Logical-left wheel speed controller.
static MotorSpeedPid s_right_speed_pid = {0}; // Logical-right wheel speed controller.

static float Motor_LimitRatio(float ratio)
{
    if (ratio > BSP_MOTOR_MAX_RATIO) {
        return BSP_MOTOR_MAX_RATIO;
    }
    if (ratio < -BSP_MOTOR_MAX_RATIO) {
        return -BSP_MOTOR_MAX_RATIO;
    }
    return ratio;
}

static float Motor_AbsFloat(float value)
{
    return (value < 0.0f) ? -value : value; // Avoid pulling in libm for a simple absolute value.
}

static int16_t Motor_LimitInt16(int32_t value)
{
    if (value > 32767) {
        return 32767; // Saturate debug speed if a long pause accumulates too many encoder ticks.
    }
    if (value < -32768) {
        return -32768; // Saturate debug speed if a long pause accumulates too many encoder ticks.
    }
    return (int16_t) value;
}

static float Motor_LimitFloat(float value, float min_value, float max_value)
{
    if (value > max_value) {
        return max_value; // Clamp upper bound for PID and command limiting.
    }
    if (value < min_value) {
        return min_value; // Clamp lower bound for PID and command limiting.
    }
    return value;
}

static float Motor_Approach(float value, float target, float step)
{
    if (value < target) {
        value += step;
        return (value > target) ? target : value;
    }
    if (value > target) {
        value -= step;
        return (value < target) ? target : value;
    }
    return value;
}

static float Motor_ApproachCommand(float value, float target)
{
    float step;

    if ((value * target) < 0.0f) {
        return Motor_Approach(value, 0.0f, BSP_MOTOR_SPEED_PWM_DECEL_SLEW_LIMIT); // Decelerate through zero before reversing.
    }

    step = (Motor_AbsFloat(target) < Motor_AbsFloat(value)) ?
           BSP_MOTOR_SPEED_PWM_DECEL_SLEW_LIMIT :
           BSP_MOTOR_SPEED_PWM_ACCEL_SLEW_LIMIT;
    return Motor_Approach(value, target, step);
}

/* 清除单轮目标、测量、积分、输出和故障监督，使下一次闭环运行不继承旧模式状态。 */
static void Motor_SpeedPidResetOne(MotorSpeedPid *pid)
{
    pid->requested_target = 0.0f; // Clear external target so reset always returns to a stopped state.
    pid->target = 0.0f; // Clear the ramped target used by the controller.
    pid->measured = 0.0f; // Clear the encoder filter history.
    pid->integral = 0.0f; // Clear stored friction compensation.
    pid->last_error = 0.0f; // Clear derivative history after mode changes.
    pid->command = 0.0f; // Clear the output command before the next closed-loop run.
    pid->p_term = 0.0f; // Clear debugger-visible P contribution.
    pid->i_term = 0.0f; // Clear debugger-visible I contribution.
    pid->startup_kick_windows = 0U; // Arm a kick only when the next nonzero target is requested.
    pid->zero_tick_windows = 0U; // Restart encoder-loss supervision.
    pid->fault = 0U; // A deliberate reset clears the latched encoder fault.
}

/*
 * 限制外部目标并处理停止/换向：清除旧方向积分和微分历史；
 * 从静止进入较高目标时仅预置一次启动 kick，弯道内侧的低速目标不会触发 kick。
 */
static void Motor_SpeedPidSetTargetOne(MotorSpeedPid *pid, float target)
{
    float previous_target = pid->requested_target;

    target = Motor_LimitFloat(target,
                              -BSP_MOTOR_SPEED_TARGET_LIMIT_CM_S,
                              BSP_MOTOR_SPEED_TARGET_LIMIT_CM_S);
    if (Motor_AbsFloat(target) < 0.1f) {
        target = 0.0f;
    }

    if ((target * pid->requested_target) < 0.0f || target == 0.0f) {
        pid->integral = 0.0f; // Direction changes and stops must not retain torque from the old target.
        pid->last_error = 0.0f; // Suppress a derivative kick after a direction/stop request.
    }
    if (target == 0.0f) {
        pid->startup_kick_windows = 0U;
    } else if (Motor_AbsFloat(target) >= BSP_MOTOR_SPEED_STARTUP_KICK_MIN_TARGET_CM_S &&
               (Motor_AbsFloat(previous_target) < 0.1f || (target * previous_target) < 0.0f)) {
        pid->startup_kick_windows = BSP_MOTOR_SPEED_STARTUP_KICK_WINDOWS;
    }
    pid->requested_target = target;
}

/*
 * 单轮 20 ms 速度控制步骤：
 * 1. 目标按斜率逼近并把编码器窗口计数换算为速度；
 * 2. 零目标逐步撤销输出并清除控制历史；
 * 3. 非零目标计算 P/I/D，积分仅在误差窗口内且不会推动输出继续饱和时更新；
 * 4. 必要时施加一次静摩擦启动 kick，之后平滑逼近控制输出；
 * 5. 在目标和 PWM 足够大但连续无编码器计数时设置实时故障位。
 */
static float Motor_SpeedPidStep(MotorSpeedPid *pid, int16_t encoder_ticks)
{
    float raw_measured;
    float target_magnitude;
    float direction;
    float error;
    float derivative;
    float candidate_integral;
    float candidate_output;
    float desired_command;
    float startup_bias;

    pid->target = Motor_Approach(pid->target,
                                 pid->requested_target,
                                 BSP_MOTOR_SPEED_TARGET_SLEW_CM_S);

    raw_measured = Motor_AbsFloat((float) encoder_ticks) * BSP_MOTOR_ENCODER_TICK_TO_CM_S;
    pid->measured += BSP_MOTOR_SPEED_FILTER_ALPHA * (raw_measured - pid->measured);

    if (Motor_AbsFloat(pid->target) < 0.1f) {
        pid->integral = 0.0f; // Zero target should not keep stale integral torque.
        pid->last_error = 0.0f; // Zero target should restart derivative history.
        pid->p_term = 0.0f;
        pid->i_term = 0.0f;
        pid->zero_tick_windows = 0U;
        pid->command = Motor_ApproachCommand(pid->command, 0.0f);
        return pid->command;
    }
    direction = (pid->target < 0.0f) ? -1.0f : 1.0f;
    target_magnitude = Motor_AbsFloat(pid->target);
    startup_bias = BSP_MOTOR_SPEED_PID_START *
                   Motor_LimitFloat(target_magnitude / BSP_MOTOR_SPEED_PID_FULL_START_CM_S,
                                    0.0f,
                                    1.0f);
    error = target_magnitude - pid->measured;
    pid->p_term = BSP_MOTOR_SPEED_PID_KP * error;
    derivative = error - pid->last_error;
    pid->last_error = error;

    candidate_integral = Motor_LimitFloat(pid->integral + error,
                                          -BSP_MOTOR_SPEED_PID_INTEGRAL_LIMIT,
                                          BSP_MOTOR_SPEED_PID_INTEGRAL_LIMIT);
    candidate_output = startup_bias +
                       pid->p_term +
                       (BSP_MOTOR_SPEED_PID_KI * candidate_integral) +
                       (BSP_MOTOR_SPEED_PID_KD * derivative);
    if (Motor_AbsFloat(error) < BSP_MOTOR_SPEED_PID_ERROR_INT_THRESHOLD &&
        ((candidate_output > 0.0f && candidate_output < BSP_MOTOR_SPEED_PID_OUTPUT_LIMIT) ||
         (candidate_output >= BSP_MOTOR_SPEED_PID_OUTPUT_LIMIT && error < 0.0f) ||
         (candidate_output <= 0.0f && error > 0.0f))) {
        pid->integral = candidate_integral; // Conditional integration prevents windup at both output rails.
    }
    pid->i_term = BSP_MOTOR_SPEED_PID_KI * pid->integral;

    desired_command = startup_bias +
                      pid->p_term +
                      pid->i_term +
                      (BSP_MOTOR_SPEED_PID_KD * derivative);
    desired_command = Motor_LimitFloat(desired_command, 0.0f, BSP_MOTOR_SPEED_PID_OUTPUT_LIMIT);
    desired_command *= direction;
    if (pid->startup_kick_windows > 0U && encoder_ticks == 0) {
        pid->command = direction * BSP_MOTOR_SPEED_STARTUP_KICK_PWM; // Match the explicit start command used by both reference projects.
        pid->startup_kick_windows--;
    } else {
        pid->startup_kick_windows = 0U; // The first encoder batch proves the wheel has crossed static friction.
        pid->command = Motor_ApproachCommand(pid->command, desired_command);
    }

    if (target_magnitude >= BSP_MOTOR_SPEED_STALL_MIN_TARGET_CM_S &&
        Motor_AbsFloat(pid->command) >= BSP_MOTOR_SPEED_STALL_MIN_PWM &&
        encoder_ticks == 0) {
        if (pid->zero_tick_windows < 0xFFFFU) {
            pid->zero_tick_windows++;
        }
        if (pid->zero_tick_windows >= BSP_MOTOR_SPEED_STALL_WINDOWS) {
            pid->fault = 1U; // Report missing feedback without abruptly braking and throwing the CCD line out of view.
        }
    } else {
        pid->zero_tick_windows = 0U;
        pid->fault = 0U; // Clear the live warning as soon as feedback or a low-drive condition returns.
    }
    return pid->command;
}

/*
 * 把一个逻辑比例映射为方向引脚和定时器 compare。
 * 负方向使用互补占空比表达，调用前先限制到允许比例范围。
 */
static void Motor_SetOne(float ratio, uint32_t dir_pin, DL_TIMER_CC_INDEX compare_index)
{
    uint32_t compare;

    ratio = Motor_LimitRatio(ratio);

    if (ratio >= 0.0f) {
        DL_GPIO_setPins(GPIO_DC_PORT, dir_pin);
        compare = (uint32_t) (ratio * (float) BSP_MOTOR_PWM_PERIOD);
    } else {
        DL_GPIO_clearPins(GPIO_DC_PORT, dir_pin);
        compare = (uint32_t) ((1.0f + ratio) * (float) BSP_MOTOR_PWM_PERIOD);
    }

    DL_Timer_setCaptureCompareValue(PWM_DC_INST, compare, compare_index);
}

static float Motor_ApplyTrim(float ratio, float dir, float forward_scale, float reverse_scale)
{
    if (ratio >= 0.0f) {
        return ratio * forward_scale * dir; // Choose trim by logical command, then apply wiring direction.
    }
    return ratio * reverse_scale * dir; // Choose trim by logical command, then apply wiring direction.
}

void Bsp_Motor_Init(void)
{
    Bsp_Motor_Disable(); // 先将 H 桥和两个 PWM 引脚强制拉低，避免初始化瞬间误动作。

    DL_GPIO_initPeripheralOutputFunction(
        GPIO_PWM_DC_C0_IOMUX, GPIO_PWM_DC_C0_IOMUX_FUNC);
    DL_GPIO_enableOutput(GPIO_PWM_DC_C0_PORT, GPIO_PWM_DC_C0_PIN);
    DL_GPIO_initPeripheralOutputFunction(
        GPIO_PWM_DC_C1_IOMUX, GPIO_PWM_DC_C1_IOMUX_FUNC);
    DL_GPIO_enableOutput(GPIO_PWM_DC_C1_PORT, GPIO_PWM_DC_C1_PIN); // 仅电机模式恢复定时器 PWM 复用，定时器仍保持停止。
}

/* 停止 PWM 计数器并清空方向输出，使驱动桥长期保持空闲；不同于主动制动。 */
void Bsp_Motor_Disable(void)
{
    DL_TimerG_stopCounter(PWM_DC_INST); // 先停止定时器，避免切换引脚复用时产生新的 PWM 边沿。
    DL_Timer_setCaptureCompareValue(PWM_DC_INST, BSP_MOTOR_PWM_PERIOD, GPIO_PWM_DC_C0_IDX);
    DL_Timer_setCaptureCompareValue(PWM_DC_INST, BSP_MOTOR_PWM_PERIOD, GPIO_PWM_DC_C1_IDX);
    DL_GPIO_clearPins(GPIO_DC_PORT, GPIO_DC_AIN0_PIN | GPIO_DC_AIN2_PIN); // 两个方向输入先拉低，使 H 桥进入空转安全状态。

    DL_GPIO_initDigitalOutput(GPIO_PWM_DC_C0_IOMUX);
    DL_GPIO_clearPins(GPIO_PWM_DC_C0_PORT, GPIO_PWM_DC_C0_PIN);
    DL_GPIO_enableOutput(GPIO_PWM_DC_C0_PORT, GPIO_PWM_DC_C0_PIN);
    DL_GPIO_initDigitalOutput(GPIO_PWM_DC_C1_IOMUX);
    DL_GPIO_clearPins(GPIO_PWM_DC_C1_PORT, GPIO_PWM_DC_C1_PIN);
    DL_GPIO_enableOutput(GPIO_PWM_DC_C1_PORT, GPIO_PWM_DC_C1_PIN); // 停用模式下将 PA12/PA13 固定为 GPIO 低电平，不能保留外设锁存状态。
}

/* 主动制动：保持 PWM 受控并让两路 H 桥输入进入短路制动组合。 */
void Bsp_Motor_Stop(void)
{
    DL_TimerG_startCounter(PWM_DC_INST); // Keep PWM running so the output level is controlled.
    DL_Timer_setCaptureCompareValue(PWM_DC_INST, 0U, GPIO_PWM_DC_C0_IDX); // Force PWM input high for active brake.
    DL_Timer_setCaptureCompareValue(PWM_DC_INST, 0U, GPIO_PWM_DC_C1_IDX); // Force PWM input high for active brake.
    DL_GPIO_setPins(GPIO_DC_PORT, GPIO_DC_AIN0_PIN | GPIO_DC_AIN2_PIN); // Both H-bridge inputs high should short-brake the motors.
}

/* 滑行：保持输出时序有效，但将桥输入置为不主动驱动的组合。 */
void Bsp_Motor_Coast(void)
{
    DL_TimerG_startCounter(PWM_DC_INST); // Keep PWM running so the output level is controlled.
    DL_Timer_setCaptureCompareValue(PWM_DC_INST, BSP_MOTOR_PWM_PERIOD, GPIO_PWM_DC_C0_IDX); // Force PWM input low for coast.
    DL_Timer_setCaptureCompareValue(PWM_DC_INST, BSP_MOTOR_PWM_PERIOD, GPIO_PWM_DC_C1_IDX); // Force PWM input low for coast.
    DL_GPIO_clearPins(GPIO_DC_PORT, GPIO_DC_AIN0_PIN | GPIO_DC_AIN2_PIN); // Both H-bridge inputs low lets the motors coast.
}

void Bsp_Motor_Set(float left_ratio, float right_ratio)
{
    DL_TimerG_startCounter(PWM_DC_INST);
    Motor_SetOne(Motor_ApplyTrim(left_ratio, BSP_MOTOR_LEFT_DIR,
                                 BSP_MOTOR_LEFT_FORWARD_SCALE,
                                 BSP_MOTOR_LEFT_REVERSE_SCALE),
                 GPIO_DC_AIN0_PIN, GPIO_PWM_DC_C0_IDX); // Logical left now drives the physical-left six-wire connector.
    Motor_SetOne(Motor_ApplyTrim(right_ratio, BSP_MOTOR_RIGHT_DIR,
                                 BSP_MOTOR_RIGHT_FORWARD_SCALE,
                                 BSP_MOTOR_RIGHT_REVERSE_SCALE),
                 GPIO_DC_AIN2_PIN, GPIO_PWM_DC_C1_IDX); // Logical right now drives the physical-right six-wire connector.
}

void Bsp_Motor_SetLeftRaw(uint8_t dir_high, uint32_t compare)
{
    if (compare > BSP_MOTOR_PWM_PERIOD) {
        compare = BSP_MOTOR_PWM_PERIOD;
    }

    DL_TimerG_startCounter(PWM_DC_INST);
    if (dir_high) {
        DL_GPIO_setPins(GPIO_DC_PORT, GPIO_DC_AIN0_PIN); // Logical left raw follows the corrected physical-left channel.
    } else {
        DL_GPIO_clearPins(GPIO_DC_PORT, GPIO_DC_AIN0_PIN); // Logical left raw follows the corrected physical-left channel.
    }
    DL_Timer_setCaptureCompareValue(PWM_DC_INST, compare, GPIO_PWM_DC_C0_IDX); // Logical left raw follows the corrected physical-left channel.
}

void Bsp_Motor_SetRightRaw(uint8_t dir_high, uint32_t compare)
{
    if (compare > BSP_MOTOR_PWM_PERIOD) {
        compare = BSP_MOTOR_PWM_PERIOD;
    }

    DL_TimerG_startCounter(PWM_DC_INST);
    if (dir_high) {
        DL_GPIO_setPins(GPIO_DC_PORT, GPIO_DC_AIN2_PIN); // Logical right raw follows the corrected physical-right channel.
    } else {
        DL_GPIO_clearPins(GPIO_DC_PORT, GPIO_DC_AIN2_PIN); // Logical right raw follows the corrected physical-right channel.
    }
    DL_Timer_setCaptureCompareValue(PWM_DC_INST, compare, GPIO_PWM_DC_C1_IDX); // Logical right raw follows the corrected physical-right channel.
}

/* 启动左右编码器硬件计数器及中断；每 10 个 A 相边沿进入一次 ISR。 */
void Bsp_Motor_EncoderInit(void)
{
    Bsp_Motor_EncoderReset();
    NVIC_EnableIRQ(COMPARE_0_INST_INT_IRQN); // PB13 old-left A phase: one IRQ per ten encoder edges.
    NVIC_EnableIRQ(COMPARE_1_INST_INT_IRQN); // PB15 old-right A phase: one IRQ per ten encoder edges.
    DL_TimerG_startCounter(COMPARE_0_INST);
    DL_TimerG_startCounter(COMPARE_1_INST);
}

/* 原子清零 ISR 累计位置，并同步清除主循环采样基线和窗口速度。 */
void Bsp_Motor_EncoderReset(void)
{
    uint32_t interrupt_state = __get_PRIMASK();

    __disable_irq();
    s_encoder_old_left_count = 0;
    s_encoder_old_right_count = 0;
    s_encoder_left_last_count = 0;
    s_encoder_right_last_count = 0;
    s_encoder_left_speed = 0;
    s_encoder_right_speed = 0;
    if (interrupt_state == 0U) {
        __enable_irq(); // 仅恢复本函数进入前处于开启状态的全局中断。
    }
}

void Bsp_Motor_GetEncoderSnapshot(Bsp_Motor_EncoderSnapshot *snapshot)
{
    uint32_t interrupt_state;

    if (snapshot == 0) {
        return;
    }

    interrupt_state = __get_PRIMASK();
    __disable_irq();
    snapshot->left_count = s_encoder_old_left_count;
    snapshot->right_count = s_encoder_old_right_count;
    if (interrupt_state == 0U) {
        __enable_irq();
    }
}

float Bsp_Motor_EncoderTicksToCm(uint32_t ticks)
{
    return (float) ticks * BSP_MOTOR_ENCODER_TICK_TO_CM;
}

/* 短暂关中断读取一致的累计计数，并计算相对上次采样的有符号 tick 增量。 */
void Bsp_Motor_EncoderSample(void)
{
    Bsp_Motor_EncoderSnapshot snapshot;
    int32_t left_delta;
    int32_t right_delta;

    Bsp_Motor_GetEncoderSnapshot(&snapshot);
    left_delta = snapshot.left_count - s_encoder_left_last_count;
    right_delta = snapshot.right_count - s_encoder_right_last_count;
    s_encoder_left_last_count = snapshot.left_count;
    s_encoder_right_last_count = snapshot.right_count;
    s_encoder_left_speed = Motor_LimitInt16(left_delta);
    s_encoder_right_speed = Motor_LimitInt16(right_delta);
}

int32_t Bsp_Motor_GetLeftEncoderCount(void)
{
    return s_encoder_old_left_count; // Logical left follows the corrected physical-left encoder channel.
}

int32_t Bsp_Motor_GetRightEncoderCount(void)
{
    return s_encoder_old_right_count; // Logical right follows the corrected physical-right encoder channel.
}

int16_t Bsp_Motor_GetLeftEncoderSpeed(void)
{
    return s_encoder_left_speed; // Return the latest logical-left signed tick delta.
}

int16_t Bsp_Motor_GetRightEncoderSpeed(void)
{
    return s_encoder_right_speed; // Return the latest logical-right signed tick delta.
}

void Bsp_Motor_SpeedPidInit(void)
{
    Bsp_Motor_SpeedPidReset(); // Initialize both wheel controllers with zero targets and zero outputs.
}

void Bsp_Motor_SpeedPidReset(void)
{
    Motor_SpeedPidResetOne(&s_left_speed_pid); // Reset logical-left speed-loop state.
    Motor_SpeedPidResetOne(&s_right_speed_pid); // Reset logical-right speed-loop state.
    Bsp_Motor_EncoderSample(); // Refresh sample baselines so the first PI update does not include old ticks.
}

void Bsp_Motor_SetSpeedTargets(float left_cm_s, float right_cm_s)
{
    Motor_SpeedPidSetTargetOne(&s_left_speed_pid, left_cm_s); // Set logical-left requested speed in cm/s.
    Motor_SpeedPidSetTargetOne(&s_right_speed_pid, right_cm_s); // Set logical-right requested speed in cm/s.
}

void Bsp_Motor_SpeedPidUpdate(void)
{
    float left_cmd;
    float right_cmd;

    Bsp_Motor_EncoderSample(); // Measure wheel ticks accumulated since the previous speed-loop update.
    left_cmd = Motor_SpeedPidStep(&s_left_speed_pid, s_encoder_left_speed);
    right_cmd = Motor_SpeedPidStep(&s_right_speed_pid, s_encoder_right_speed);
    Bsp_Motor_Set(left_cmd, right_cmd); // Keep running at the 0.35 baseline cap while fault bits diagnose missing feedback.
}

void Bsp_Motor_SpeedPidStop(void)
{
    Bsp_Motor_Stop(); // Use active brake so the speed loop test stops promptly.
    Bsp_Motor_SetSpeedTargets(0.0f, 0.0f); // Clear targets after stopping.
    Bsp_Motor_SpeedPidReset(); // Clear PI state after the active stop.
}

float Bsp_Motor_GetLeftSpeedTarget(void)
{
    return s_left_speed_pid.target; // Expose logical-left slew-limited target in cm/s.
}

float Bsp_Motor_GetRightSpeedTarget(void)
{
    return s_right_speed_pid.target; // Expose logical-right slew-limited target in cm/s.
}

float Bsp_Motor_GetLeftSpeedCommand(void)
{
    return s_left_speed_pid.command; // Expose logical-left generated PWM ratio for Watch/Expressions.
}

float Bsp_Motor_GetRightSpeedCommand(void)
{
    return s_right_speed_pid.command; // Expose logical-right generated PWM ratio for Watch/Expressions.
}

float Bsp_Motor_GetLeftMeasuredSpeed(void)
{
    return s_left_speed_pid.measured; // Expose filtered logical-left speed in cm/s.
}

float Bsp_Motor_GetRightMeasuredSpeed(void)
{
    return s_right_speed_pid.measured; // Expose filtered logical-right speed in cm/s.
}

float Bsp_Motor_GetLeftSpeedPTerm(void)
{
    return s_left_speed_pid.p_term;
}

float Bsp_Motor_GetRightSpeedPTerm(void)
{
    return s_right_speed_pid.p_term;
}

float Bsp_Motor_GetLeftSpeedITerm(void)
{
    return s_left_speed_pid.i_term;
}

float Bsp_Motor_GetRightSpeedITerm(void)
{
    return s_right_speed_pid.i_term;
}

uint32_t Bsp_Motor_GetSpeedFaults(void)
{
    return ((uint32_t) s_left_speed_pid.fault) |
           (((uint32_t) s_right_speed_pid.fault) << 1U); // Bit 0 left, bit 1 right.
}

/*
 * 左轮编码器 ISR：硬件累计一批 A 相边沿后触发，读取 B 相判断方向并更新软件位置。
 * ISR 不计算速度、不打印日志，窗口速度由 Bsp_Motor_EncoderSample() 在主循环计算。
 */
void COMPARE_0_INST_IRQHandler(void)
{
    if (DL_TimerG_getPendingInterrupt(COMPARE_0_INST) == DL_TIMERG_IIDX_LOAD) {
        if (DL_GPIO_readPins(GPIO_ENCODER_PORT, GPIO_ENCODER_PIN_1B_PIN) == 0U) {
            s_encoder_old_left_count++;
        } else {
            s_encoder_old_left_count--;
        }
    }
}

/* 右轮编码器 ISR，与左轮采用相同的批量 A 相计数和 B 相方向判定。 */
void COMPARE_1_INST_IRQHandler(void)
{
    if (DL_TimerG_getPendingInterrupt(COMPARE_1_INST) == DL_TIMERG_IIDX_LOAD) {
        if (DL_GPIO_readPins(GPIO_ENCODER_PORT, GPIO_ENCODER_PIN_2B_PIN) == 0U) {
            s_encoder_old_right_count++;
        } else {
            s_encoder_old_right_count--;
        }
    }
}
