#include "bsp_motor.h"

#include <stdint.h>
#include "ti/driverlib/m0p/dl_interrupt.h"
#include "ti_msp_dl_config.h"

#define BSP_MOTOR_PWM_PERIOD 10000U
#define BSP_MOTOR_MAX_RATIO  0.80f
#define BSP_MOTOR_LEFT_DIR   -1.0f // New-left wheel uses the old-right channel, so positive command must run old-right reverse.
#define BSP_MOTOR_RIGHT_DIR  -1.0f // New-right wheel uses the old-left channel, so positive command must run old-left reverse.
#define BSP_MOTOR_LEFT_FORWARD_SCALE  1.00f // New-left forward uses old-right reverse trim.
#define BSP_MOTOR_RIGHT_FORWARD_SCALE 0.85f // New-right forward uses old-left reverse trim.
#define BSP_MOTOR_LEFT_REVERSE_SCALE  1.00f // New-left reverse uses old-right forward trim.
#define BSP_MOTOR_RIGHT_REVERSE_SCALE 0.91f // New-right reverse uses old-left forward trim.
#define BSP_MOTOR_ENCODER_OLD_LEFT_A_PIN DL_GPIO_PIN_13 // PB13 is the 2025-board old-left encoder A phase.
#define BSP_MOTOR_ENCODER_OLD_RIGHT_A_PIN DL_GPIO_PIN_15 // PB15 is the 2025-board old-right encoder A phase.
#define BSP_MOTOR_ENCODER_OLD_LEFT_B_PIN DL_GPIO_PIN_20 // PB20 is the 2025-board old-left encoder B phase.
#define BSP_MOTOR_ENCODER_OLD_RIGHT_B_PIN DL_GPIO_PIN_17 // PB17 is the 2025-board old-right encoder B phase.
#define BSP_MOTOR_ENCODER_A_MASK (BSP_MOTOR_ENCODER_OLD_LEFT_A_PIN | BSP_MOTOR_ENCODER_OLD_RIGHT_A_PIN) // Interrupt only on A phases.
#define BSP_MOTOR_SPEED_PID_KP 0.012f // Convert encoder tick error into a PWM-ratio correction.
#define BSP_MOTOR_SPEED_PID_KI 0.0012f // Add a small integral term to overcome low-speed friction.
#define BSP_MOTOR_SPEED_PID_KD 0.0f // Keep derivative disabled until encoder tick noise is measured.
#define BSP_MOTOR_SPEED_PID_KFF 0.025f // Feed-forward PWM ratio per encoder tick per sample.
#define BSP_MOTOR_SPEED_PID_START 0.08f // Minimum PWM bias helps the wheel start before the PI term builds.
#define BSP_MOTOR_SPEED_PID_INTEGRAL_LIMIT 80.0f // Bound integral so a stalled wheel cannot wind up indefinitely.
#define BSP_MOTOR_SPEED_PID_OUTPUT_LIMIT 0.60f // Keep closed-loop speed tests slower than the open-loop hard limit.

typedef struct {
    float target; // Target encoder ticks per sample for one logical wheel.
    float integral; // Accumulated speed error for low-speed friction compensation.
    float last_error; // Previous speed error used by the derivative term.
    float command; // Latest PWM ratio generated by the speed PI loop.
} MotorSpeedPid;

static volatile int32_t s_encoder_old_left_count = 0; // Raw old-left encoder position from PB13/PB20.
static volatile int32_t s_encoder_old_right_count = 0; // Raw old-right encoder position from PB15/PB17.
static int32_t s_encoder_left_last_count = 0; // Previous logical-left count used to form sample speed.
static int32_t s_encoder_right_last_count = 0; // Previous logical-right count used to form sample speed.
static int16_t s_encoder_left_speed = 0; // Latest logical-left signed tick delta per sample.
static int16_t s_encoder_right_speed = 0; // Latest logical-right signed tick delta per sample.
static MotorSpeedPid s_left_speed_pid = {0}; // Logical-left wheel speed controller.
static MotorSpeedPid s_right_speed_pid = {0}; // Logical-right wheel speed controller.

static float Motor_LimitRatio(float ratio)
{
    if (ratio > BSP_MOTOR_MAX_RATIO) {
        return BSP_MOTOR_MAX_RATIO;
    }
    if (ratio < -BSP_MOTOR_MAX_RATIO) {
        return -BSP_MOTOR_MAX_RATIO;
    }
    return ratio;
}

static float Motor_AbsFloat(float value)
{
    return (value < 0.0f) ? -value : value; // Avoid pulling in libm for a simple absolute value.
}

static int16_t Motor_LimitInt16(int32_t value)
{
    if (value > 32767) {
        return 32767; // Saturate debug speed if a long pause accumulates too many encoder ticks.
    }
    if (value < -32768) {
        return -32768; // Saturate debug speed if a long pause accumulates too many encoder ticks.
    }
    return (int16_t) value;
}

static float Motor_LimitFloat(float value, float min_value, float max_value)
{
    if (value > max_value) {
        return max_value; // Clamp upper bound for PID and command limiting.
    }
    if (value < min_value) {
        return min_value; // Clamp lower bound for PID and command limiting.
    }
    return value;
}

static float Motor_MeasuredSpeedForTarget(float target, int16_t raw_speed)
{
    float magnitude = (float) ((raw_speed < 0) ? -raw_speed : raw_speed);

    if (target < 0.0f) {
        return -magnitude; // Use commanded direction as speed sign so reversed encoder wiring cannot destabilize PI.
    }
    return magnitude; // Forward targets compare against positive encoder tick magnitude.
}

static void Motor_SpeedPidResetOne(MotorSpeedPid *pid)
{
    pid->target = 0.0f; // Clear target so the controller starts from a stopped state.
    pid->integral = 0.0f; // Clear stored friction compensation.
    pid->last_error = 0.0f; // Clear derivative history after mode changes.
    pid->command = 0.0f; // Clear the output command before the next closed-loop run.
}

static float Motor_SpeedPidStep(MotorSpeedPid *pid, float measured)
{
    float error;
    float derivative;
    float base;

    if (Motor_AbsFloat(pid->target) < 0.1f) {
        pid->integral = 0.0f; // Zero target should not keep stale integral torque.
        pid->last_error = 0.0f; // Zero target should restart derivative history.
        pid->command = 0.0f; // Zero target maps to zero motor command.
        return 0.0f;
    }

    error = pid->target - measured;
    pid->integral += error;
    pid->integral = Motor_LimitFloat(pid->integral,
                                     -BSP_MOTOR_SPEED_PID_INTEGRAL_LIMIT,
                                     BSP_MOTOR_SPEED_PID_INTEGRAL_LIMIT); // Limit integral windup while a wheel is stuck.
    derivative = error - pid->last_error;
    pid->last_error = error;

    base = pid->target * BSP_MOTOR_SPEED_PID_KFF;
    if (pid->target > 0.0f) {
        base += BSP_MOTOR_SPEED_PID_START; // Add a positive startup bias for forward motion.
    } else {
        base -= BSP_MOTOR_SPEED_PID_START; // Add a negative startup bias for reverse motion.
    }

    pid->command = base +
                   (BSP_MOTOR_SPEED_PID_KP * error) +
                   (BSP_MOTOR_SPEED_PID_KI * pid->integral) +
                   (BSP_MOTOR_SPEED_PID_KD * derivative);
    pid->command = Motor_LimitFloat(pid->command,
                                    -BSP_MOTOR_SPEED_PID_OUTPUT_LIMIT,
                                    BSP_MOTOR_SPEED_PID_OUTPUT_LIMIT); // Keep speed-loop output within a test-safe range.
    return pid->command;
}

static void Motor_SetOne(float ratio, uint32_t dir_pin, DL_TIMER_CC_INDEX compare_index)
{
    uint32_t compare;

    ratio = Motor_LimitRatio(ratio);

    if (ratio >= 0.0f) {
        DL_GPIO_setPins(GPIO_DC_PORT, dir_pin);
        compare = (uint32_t) (ratio * (float) BSP_MOTOR_PWM_PERIOD);
    } else {
        DL_GPIO_clearPins(GPIO_DC_PORT, dir_pin);
        compare = (uint32_t) ((1.0f + ratio) * (float) BSP_MOTOR_PWM_PERIOD);
    }

    DL_Timer_setCaptureCompareValue(PWM_DC_INST, compare, compare_index);
}

static float Motor_ApplyTrim(float ratio, float dir, float forward_scale, float reverse_scale)
{
    if (ratio >= 0.0f) {
        return ratio * forward_scale * dir; // Choose trim by logical command, then apply wiring direction.
    }
    return ratio * reverse_scale * dir; // Choose trim by logical command, then apply wiring direction.
}

void Bsp_Motor_Init(void)
{
    Bsp_Motor_Disable(); // Leave the bridge electrically idle until a motion command is issued.
}

void Bsp_Motor_Disable(void)
{
    DL_TimerG_stopCounter(PWM_DC_INST); // Stop PWM so debug/CCD modes cannot accidentally drive the motors.
    DL_Timer_setCaptureCompareValue(PWM_DC_INST, BSP_MOTOR_PWM_PERIOD, GPIO_PWM_DC_C0_IDX); // Keep PWM command at zero-drive side.
    DL_Timer_setCaptureCompareValue(PWM_DC_INST, BSP_MOTOR_PWM_PERIOD, GPIO_PWM_DC_C1_IDX); // Keep PWM command at zero-drive side.
    DL_GPIO_clearPins(GPIO_DC_PORT, GPIO_DC_AIN0_PIN | GPIO_DC_AIN2_PIN); // Clear direction pins so the H-bridge is idle.
}

void Bsp_Motor_Stop(void)
{
    DL_TimerG_startCounter(PWM_DC_INST); // Keep PWM running so the output level is controlled.
    DL_Timer_setCaptureCompareValue(PWM_DC_INST, 0U, GPIO_PWM_DC_C0_IDX); // Force PWM input high for active brake.
    DL_Timer_setCaptureCompareValue(PWM_DC_INST, 0U, GPIO_PWM_DC_C1_IDX); // Force PWM input high for active brake.
    DL_GPIO_setPins(GPIO_DC_PORT, GPIO_DC_AIN0_PIN | GPIO_DC_AIN2_PIN); // Both H-bridge inputs high should short-brake the motors.
}

void Bsp_Motor_Coast(void)
{
    DL_TimerG_startCounter(PWM_DC_INST); // Keep PWM running so the output level is controlled.
    DL_Timer_setCaptureCompareValue(PWM_DC_INST, BSP_MOTOR_PWM_PERIOD, GPIO_PWM_DC_C0_IDX); // Force PWM input low for coast.
    DL_Timer_setCaptureCompareValue(PWM_DC_INST, BSP_MOTOR_PWM_PERIOD, GPIO_PWM_DC_C1_IDX); // Force PWM input low for coast.
    DL_GPIO_clearPins(GPIO_DC_PORT, GPIO_DC_AIN0_PIN | GPIO_DC_AIN2_PIN); // Both H-bridge inputs low lets the motors coast.
}

void Bsp_Motor_Set(float left_ratio, float right_ratio)
{
    DL_TimerG_startCounter(PWM_DC_INST);
    Motor_SetOne(Motor_ApplyTrim(right_ratio, BSP_MOTOR_RIGHT_DIR,
                                 BSP_MOTOR_RIGHT_FORWARD_SCALE,
                                 BSP_MOTOR_RIGHT_REVERSE_SCALE),
                 GPIO_DC_AIN0_PIN, GPIO_PWM_DC_C0_IDX); // Logical right wheel is wired to the old-left motor channel.
    Motor_SetOne(Motor_ApplyTrim(left_ratio, BSP_MOTOR_LEFT_DIR,
                                 BSP_MOTOR_LEFT_FORWARD_SCALE,
                                 BSP_MOTOR_LEFT_REVERSE_SCALE),
                 GPIO_DC_AIN2_PIN, GPIO_PWM_DC_C1_IDX); // Logical left wheel is wired to the old-right motor channel.
}

void Bsp_Motor_SetLeftRaw(uint8_t dir_high, uint32_t compare)
{
    if (compare > BSP_MOTOR_PWM_PERIOD) {
        compare = BSP_MOTOR_PWM_PERIOD;
    }

    DL_TimerG_startCounter(PWM_DC_INST);
    if (dir_high) {
        DL_GPIO_setPins(GPIO_DC_PORT, GPIO_DC_AIN2_PIN); // Logical left raw drives the old-right motor channel.
    } else {
        DL_GPIO_clearPins(GPIO_DC_PORT, GPIO_DC_AIN2_PIN); // Logical left raw drives the old-right motor channel.
    }
    DL_Timer_setCaptureCompareValue(PWM_DC_INST, compare, GPIO_PWM_DC_C1_IDX); // Logical left raw drives the old-right motor channel.
}

void Bsp_Motor_SetRightRaw(uint8_t dir_high, uint32_t compare)
{
    if (compare > BSP_MOTOR_PWM_PERIOD) {
        compare = BSP_MOTOR_PWM_PERIOD;
    }

    DL_TimerG_startCounter(PWM_DC_INST);
    if (dir_high) {
        DL_GPIO_setPins(GPIO_DC_PORT, GPIO_DC_AIN0_PIN); // Logical right raw drives the old-left motor channel.
    } else {
        DL_GPIO_clearPins(GPIO_DC_PORT, GPIO_DC_AIN0_PIN); // Logical right raw drives the old-left motor channel.
    }
    DL_Timer_setCaptureCompareValue(PWM_DC_INST, compare, GPIO_PWM_DC_C0_IDX); // Logical right raw drives the old-left motor channel.
}

void Bsp_Motor_EncoderInit(void)
{
    DL_GPIO_initDigitalInputFeatures(IOMUX_PINCM30, DL_GPIO_INVERSION_DISABLE,
                                     DL_GPIO_RESISTOR_PULL_UP,
                                     DL_GPIO_HYSTERESIS_ENABLE,
                                     DL_GPIO_WAKEUP_DISABLE); // PB13 old-left encoder A input.
    DL_GPIO_initDigitalInputFeatures(IOMUX_PINCM32, DL_GPIO_INVERSION_DISABLE,
                                     DL_GPIO_RESISTOR_PULL_UP,
                                     DL_GPIO_HYSTERESIS_ENABLE,
                                     DL_GPIO_WAKEUP_DISABLE); // PB15 old-right encoder A input.
    DL_GPIO_initDigitalInputFeatures(IOMUX_PINCM48, DL_GPIO_INVERSION_DISABLE,
                                     DL_GPIO_RESISTOR_PULL_UP,
                                     DL_GPIO_HYSTERESIS_ENABLE,
                                     DL_GPIO_WAKEUP_DISABLE); // PB20 old-left encoder B input.
    DL_GPIO_initDigitalInputFeatures(IOMUX_PINCM43, DL_GPIO_INVERSION_DISABLE,
                                     DL_GPIO_RESISTOR_PULL_UP,
                                     DL_GPIO_HYSTERESIS_ENABLE,
                                     DL_GPIO_WAKEUP_DISABLE); // PB17 old-right encoder B input.

    DL_GPIO_setLowerPinsInputFilter(GPIOB,
                                    DL_GPIO_PIN_13_INPUT_FILTER_8_CYCLES |
                                    DL_GPIO_PIN_15_INPUT_FILTER_8_CYCLES); // Debounce A-phase interrupts like the 2025 SysConfig.
    DL_GPIO_setUpperPinsInputFilter(GPIOB,
                                    DL_GPIO_PIN_17_INPUT_FILTER_8_CYCLES |
                                    DL_GPIO_PIN_20_INPUT_FILTER_8_CYCLES); // Filter B phases so direction reads are stable.
    DL_GPIO_setLowerPinsPolarity(GPIOB,
                                 DL_GPIO_PIN_13_EDGE_RISE |
                                 DL_GPIO_PIN_15_EDGE_RISE); // Count one edge per encoder cycle first to reduce interrupt load.
    DL_GPIO_clearInterruptStatus(GPIOB, BSP_MOTOR_ENCODER_A_MASK); // Clear stale encoder edges before enabling the IRQ.
    DL_GPIO_enableInterrupt(GPIOB, BSP_MOTOR_ENCODER_A_MASK); // Enable A-phase GPIO interrupts for both encoder channels.
    NVIC_EnableIRQ(GPIOB_INT_IRQn); // Route GPIOB group interrupts into GROUP1_IRQHandler.
    Bsp_Motor_EncoderReset();
}

void Bsp_Motor_EncoderReset(void)
{
    __disable_irq();
    s_encoder_old_left_count = 0; // Clear raw old-left encoder position atomically.
    s_encoder_old_right_count = 0; // Clear raw old-right encoder position atomically.
    __enable_irq();
    s_encoder_left_last_count = 0; // Reset logical-left sample baseline.
    s_encoder_right_last_count = 0; // Reset logical-right sample baseline.
    s_encoder_left_speed = 0; // Reset logical-left sample speed.
    s_encoder_right_speed = 0; // Reset logical-right sample speed.
}

void Bsp_Motor_EncoderSample(void)
{
    int32_t left_count;
    int32_t right_count;
    int32_t left_delta;
    int32_t right_delta;

    __disable_irq();
    right_count = s_encoder_old_left_count; // Logical right wheel is wired to the 2025 old-left motor/encoder channel.
    left_count = s_encoder_old_right_count; // Logical left wheel is wired to the 2025 old-right motor/encoder channel.
    __enable_irq();

    left_delta = left_count - s_encoder_left_last_count;
    right_delta = right_count - s_encoder_right_last_count;
    s_encoder_left_last_count = left_count; // Store baseline for the next speed sample.
    s_encoder_right_last_count = right_count; // Store baseline for the next speed sample.
    s_encoder_left_speed = Motor_LimitInt16(left_delta); // Expose signed raw ticks for direction checks.
    s_encoder_right_speed = Motor_LimitInt16(right_delta); // Expose signed raw ticks for direction checks.
}

int32_t Bsp_Motor_GetLeftEncoderCount(void)
{
    return s_encoder_old_right_count; // Logical left maps to the 2025 old-right encoder channel.
}

int32_t Bsp_Motor_GetRightEncoderCount(void)
{
    return s_encoder_old_left_count; // Logical right maps to the 2025 old-left encoder channel.
}

int16_t Bsp_Motor_GetLeftEncoderSpeed(void)
{
    return s_encoder_left_speed; // Return the latest logical-left signed tick delta.
}

int16_t Bsp_Motor_GetRightEncoderSpeed(void)
{
    return s_encoder_right_speed; // Return the latest logical-right signed tick delta.
}

void Bsp_Motor_SpeedPidInit(void)
{
    Bsp_Motor_SpeedPidReset(); // Initialize both wheel controllers with zero targets and zero outputs.
}

void Bsp_Motor_SpeedPidReset(void)
{
    Motor_SpeedPidResetOne(&s_left_speed_pid); // Reset logical-left speed-loop state.
    Motor_SpeedPidResetOne(&s_right_speed_pid); // Reset logical-right speed-loop state.
    Bsp_Motor_EncoderSample(); // Refresh sample baselines so the first PI update does not include old ticks.
}

void Bsp_Motor_SetSpeedTargets(float left_ticks, float right_ticks)
{
    s_left_speed_pid.target = left_ticks; // Set logical-left speed target in encoder ticks per sample.
    s_right_speed_pid.target = right_ticks; // Set logical-right speed target in encoder ticks per sample.
}

void Bsp_Motor_SpeedPidUpdate(void)
{
    float left_measured;
    float right_measured;
    float left_cmd;
    float right_cmd;

    Bsp_Motor_EncoderSample(); // Measure wheel ticks accumulated since the previous speed-loop update.
    left_measured = Motor_MeasuredSpeedForTarget(s_left_speed_pid.target, s_encoder_left_speed);
    right_measured = Motor_MeasuredSpeedForTarget(s_right_speed_pid.target, s_encoder_right_speed);
    left_cmd = Motor_SpeedPidStep(&s_left_speed_pid, left_measured);
    right_cmd = Motor_SpeedPidStep(&s_right_speed_pid, right_measured);
    Bsp_Motor_Set(left_cmd, right_cmd); // Apply closed-loop PWM ratios through the verified logical motor mapping.
}

void Bsp_Motor_SpeedPidStop(void)
{
    Bsp_Motor_Stop(); // Use active brake so the speed loop test stops promptly.
    Bsp_Motor_SetSpeedTargets(0.0f, 0.0f); // Clear targets after stopping.
    Bsp_Motor_SpeedPidReset(); // Clear PI state after the active stop.
}

float Bsp_Motor_GetLeftSpeedTarget(void)
{
    return s_left_speed_pid.target; // Expose logical-left target for Watch/Expressions.
}

float Bsp_Motor_GetRightSpeedTarget(void)
{
    return s_right_speed_pid.target; // Expose logical-right target for Watch/Expressions.
}

float Bsp_Motor_GetLeftSpeedCommand(void)
{
    return s_left_speed_pid.command; // Expose logical-left generated PWM ratio for Watch/Expressions.
}

float Bsp_Motor_GetRightSpeedCommand(void)
{
    return s_right_speed_pid.command; // Expose logical-right generated PWM ratio for Watch/Expressions.
}

void GROUP1_IRQHandler(void)
{
    if (DL_Interrupt_getPendingGroup(DL_INTERRUPT_GROUP_1) == DL_INTERRUPT_GROUP1_IIDX_GPIOB) {
        uint32_t status = DL_GPIO_getEnabledInterruptStatus(GPIOB, BSP_MOTOR_ENCODER_A_MASK);

        DL_GPIO_clearInterruptStatus(GPIOB, status); // Clear both encoder A-phase interrupts before doing software counting.
        if ((status & BSP_MOTOR_ENCODER_OLD_LEFT_A_PIN) != 0U) {
            if ((DL_GPIO_readPins(GPIOB, BSP_MOTOR_ENCODER_OLD_LEFT_B_PIN)) == 0U) {
                s_encoder_old_left_count++; // Match the 2025 A/B direction convention for old-left encoder.
            } else {
                s_encoder_old_left_count--; // Match the 2025 A/B direction convention for old-left encoder.
            }
        }
        if ((status & BSP_MOTOR_ENCODER_OLD_RIGHT_A_PIN) != 0U) {
            if ((DL_GPIO_readPins(GPIOB, BSP_MOTOR_ENCODER_OLD_RIGHT_B_PIN)) == 0U) {
                s_encoder_old_right_count++; // Match the 2025 A/B direction convention for old-right encoder.
            } else {
                s_encoder_old_right_count--; // Match the 2025 A/B direction convention for old-right encoder.
            }
        }
    }
}
